#!/usr/bin/env python3
"""
Generate the FAKK2 import bridge table.

The lifted code calls every Win32 import as RECOMP_ICALL(MEM32(iat_slot)). We
patch each IAT slot at startup with a sentinel, so the dispatcher can map it
back to an entry in the table this script emits, and forward the call to the
REAL Win32 function -- FAKK2 is a Win32 program and we are a Win32 process, so
almost nothing needs emulating. Only the calling convention has to be bridged:
arguments come off the simulated stack.

Stdcall argument sizes are not in the PE (kernel32 exports undecorated names),
but they ARE in the Windows SDK import libraries, which keep the decorated
`_CreateFileA@28` symbol. So the arg counts are read out of the SDK rather than
maintained by hand.

It also emits a name -> argument-count table for the DLLs the game resolves
functions from at runtime (opengl32 above all), so a pointer that arrived via
GetProcAddress can be called with the right stack cleanup too.

Output: src/game/imports_gen.c, src/game/stdcall_argc.c
Usage:  py -3 gen_imports.py [_extracted/fakk2.exe] [src/game/imports_gen.c]
"""
import glob
import os
import re
import sys

_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_here, 'tools', 'pcrecomp', 'tools', 'pe'))
from pe_analyze import analyze_pe, build_iat_map

SDK_LIBS = r'C:\Program Files (x86)\Windows Kits\10\Lib\*\um\x86\*.lib'

# Cdecl imports: the CALLER cleans the stack, so the bridge must not pop the
# arguments. Everything else in a Win32 import table is stdcall.
CDECL = {'wsprintfA', 'wsprintfW'}

# DLLs the game resolves functions from at runtime, via LoadLibrary +
# GetProcAddress -- opengl32 is the whole renderer. Their exports go into the
# runtime name -> argument-count table.
DYNAMIC_DLLS = {
    'kernel32', 'user32', 'gdi32', 'opengl32', 'glu32', 'winmm', 'advapi32',
    'ole32', 'oleaut32', 'ddraw', 'dsound', 'dinput', 'dinput8', 'wsock32',
    'ws2_32', 'shell32', 'version', 'comctl32', 'comdlg32',
}


def stdcall_arg_bytes(only=None):
    """{name: bytes of arguments} from the decorated symbols in the SDK libs."""
    out = {}
    libs = sorted(glob.glob(SDK_LIBS))
    if not libs:
        print('WARNING: no Windows SDK x86 import libraries found; '
              'every arg count falls back to 0', file=sys.stderr)
    for lib in libs:
        if only and os.path.splitext(os.path.basename(lib))[0].lower() not in only:
            continue
        for name, n in re.findall(rb'_([A-Za-z_][A-Za-z0-9_]*)@(\d+)', open(lib, 'rb').read()):
            out[name.decode()] = int(n)
    return out


def write_dynamic_table(path):
    """Argument counts for everything GetProcAddress might hand back."""
    tbl = sorted(stdcall_arg_bytes(DYNAMIC_DLLS).items())
    L = ['/* stdcall argument counts, from the Windows SDK import libraries.',
         ' * AUTO-GENERATED by gen_imports.py - DO NOT EDIT.',
         ' *',
         ' * Sorted by name: bridge_dynamic() binary-searches it to find how much',
         ' * stack a function resolved through GetProcAddress cleans up. */',
         '#include "imports.h"', '',
         'const fakk_argc_t g_fakk_argc[] = {']
    L += [f'    {{ "{n}", {b // 4} }},' for n, b in tbl]
    L += ['};', f'const unsigned g_fakk_argc_count = {len(tbl)};', '']
    open(path, 'w').write(chr(10).join(L))
    print(f'wrote {path}: {len(tbl)} stdcall signatures')


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_here, '_extracted', 'fakk2.exe')
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(_here, 'src', 'game', 'imports_gen.c')

    rows = sorted(build_iat_map(analyze_pe(exe)).items())   # (va, (dll, name))
    argb = stdcall_arg_bytes()

    unknown = sorted({n for _, (_, n) in rows if n not in argb and n not in CDECL})

    L = ['/* FAKK2 import bridge table - AUTO-GENERATED, DO NOT EDIT */',
         f'/* Regenerate: py -3 gen_imports.py {os.path.basename(exe)} */',
         '#include "imports.h"', '',
         f'/* {len(rows)} imports from '
         f'{len({d for _, (d, _) in rows})} DLLs in {os.path.basename(exe)} */',
         'const fakk_import_t g_fakk_imports[] = {']
    for va, (dll, name) in rows:
        nargs = -1 if name in CDECL else argb.get(name, 0) // 4
        note = '' if name in argb or name in CDECL else '  /* arg count unknown */'
        L.append(f'    {{ 0x{va:08X}u, "{dll}", "{name}", {nargs} }},{note}')
    L += ['};', f'const unsigned g_fakk_import_count = {len(rows)};', '']

    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w').write('\n'.join(L))
    print(f'wrote {out}: {len(rows)} imports')
    write_dynamic_table(os.path.join(os.path.dirname(out), 'stdcall_argc.c'))
    if unknown:
        print(f'{len(unknown)} without a decorated SDK symbol (arg count 0): '
              + ', '.join(unknown))


if __name__ == '__main__':
    main()
